Functionality: CRUD methods
elfin-git/To-Do-List pull request #3
Opened 2022-08-13 16:13 UTC by elfin-git

- Implemented a function for adding a new task (add a new element to the array).
- Implemented a function for deleting a task (remove an element from the array).
- Implemented a function for editing task descriptions.
- All changes to the To Do List are be saved in local storage.
- Index of remaining items is updated after removing one task.

2022-08-13 16:25 UTC, ahmetbozaci requested changes
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)

 @elfin-git  ✋🏼 

#### Your project is great. You are almost done. However, there are some issues you should fix. Please fix them then your project will be approved.

___ 

### 💯  Highlights 💯
- Your git-flow is correct. ✔️
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️
- I can add and remove to-do items.✔️
- If ı  remove todo item index updated.✔️
- All todo items are saved in the localstorage.✔️
___


### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._

___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
![image](https://user-images.githubusercontent.com/38635158/184502557-198c1ee2-78ce-4094-b40e-75f4defb832f.png)

___

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._


___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-08-13 16:25 UTC, ahmetbozaci commented on src/assets/create.js
> +         <span class="span" contenteditable="true">${task.description}</span>
- [ ] I can edit the to-do item but it is not changing in the local storage. Kindly fix it.
![image](https://user-images.githubusercontent.com/38635158/184502537-73a089ea-f2b8-4120-ad94-baeb99920f60.png)

2022-08-18 07:19 UTC, degisew reviewed
Hi @elfin-git 
Great job so far 👏 👏 

You are almost there but there are still some issues that going to be fixed for your next project.

### Required changes ♻️ 
check the comment under the review.

2022-08-18 07:19 UTC, degisew commented on dist/index.html
>          <div id="list-items">
Kindly add a proper indentation.

2022-08-18 07:19 UTC, degisew commented on src/index.js
make sure you put a blank line for reason.

2022-08-18 20:21 UTC, gtekle requested changes
Hi @elfin-git 👋 , 

# STATUS: Changes Requested 🔴 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![this close](https://user-images.githubusercontent.com/44057863/185486852-bc3bf1c3-8e7c-4033-8b5b-3c01e5c97a3a.gif)

 ## Highlights
✔️ Meaningful commit messages
✔️ Good use of Github flow
✔️ Descriptive PR summary
✔️ Professional ReadMe

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] As stated by the previous reviewer, kindly save the updated task description into localStorage. Right now, the update is lost if you refresh the page. You may also check localStorage under applications tab in Chrome dev tools. 
![image](https://user-images.githubusercontent.com/44057863/185486817-266cde2c-4ec2-4e81-ae4a-1bb782a0f38f.png)


## Optional suggestions

- [ OPTIONAL ] In future projects, kindly use more descriptive branch names. In this case, for example, `functionality` is not a descriptive enough branch name. You could have used some thing like `feature/task-crud-operations`

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 20:31 UTC, elfin-git commented
@gtekle , It is working fine on my end, let me try opening it on chrome, I am currently using firefox

2022-08-18 20:52 UTC, elfin-git commented
The event listener for the task has been changed, so with every change you make, the local storage is updated, please reload your local storage if you are on chrome. For now, everything is working fine on both  firefox and chrome

2022-08-18 20:57 UTC, elmar8287 approved these changes
Hi, @elfin-git.

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

### Highlights

- Actually, local storage is working 👍 🥇 

### Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
### Please, remember to tag me (@elmar8287) in your question so I can receive the notification 👍 
![giphy](https://user-images.githubusercontent.com/49064106/180751457-52107e57-31fd-486c-97fe-bcccf4e449af.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 21:08 UTC, merged